//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Assets\Scripts\Aff\ArcaeaFileFormat.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Arcade.Aff {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ArcaeaFileFormatParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IArcaeaFileFormatListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ArcaeaFileFormatParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ArcaeaFileFormatParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValues([NotNull] ArcaeaFileFormatParser.ValuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValues([NotNull] ArcaeaFileFormatParser.ValuesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.event"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvent([NotNull] ArcaeaFileFormatParser.EventContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.event"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvent([NotNull] ArcaeaFileFormatParser.EventContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem([NotNull] ArcaeaFileFormatParser.ItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem([NotNull] ArcaeaFileFormatParser.ItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.subevents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubevents([NotNull] ArcaeaFileFormatParser.SubeventsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.subevents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubevents([NotNull] ArcaeaFileFormatParser.SubeventsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSegment([NotNull] ArcaeaFileFormatParser.SegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSegment([NotNull] ArcaeaFileFormatParser.SegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] ArcaeaFileFormatParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] ArcaeaFileFormatParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] ArcaeaFileFormatParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] ArcaeaFileFormatParser.FileContext context);
}
} // namespace Arcade.Aff
