//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Assets\Scripts\Aff\ArcaeaFileFormat.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IArcaeaFileFormatListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class ArcaeaFileFormatBaseListener : IArcaeaFileFormatListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] ArcaeaFileFormatParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] ArcaeaFileFormatParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValues([NotNull] ArcaeaFileFormatParser.ValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValues([NotNull] ArcaeaFileFormatParser.ValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.event"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvent([NotNull] ArcaeaFileFormatParser.EventContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.event"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvent([NotNull] ArcaeaFileFormatParser.EventContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem([NotNull] ArcaeaFileFormatParser.ItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem([NotNull] ArcaeaFileFormatParser.ItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.subevents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubevents([NotNull] ArcaeaFileFormatParser.SubeventsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.subevents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubevents([NotNull] ArcaeaFileFormatParser.SubeventsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.segment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSegment([NotNull] ArcaeaFileFormatParser.SegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.segment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSegment([NotNull] ArcaeaFileFormatParser.SegmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcaeaFileFormatParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] ArcaeaFileFormatParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcaeaFileFormatParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] ArcaeaFileFormatParser.BodyContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
