//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/ArcadeInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Arcade.Compose
{
    public partial class @AdeInputControl : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @AdeInputControl()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""ArcadeInput"",
    ""maps"": [
        {
            ""name"": ""Arcade Hotkey"",
            ""id"": ""cd950ed4-bcec-4ef6-b1f8-1c8be8aefa42"",
            ""actions"": [
                {
                    ""name"": ""Save"",
                    ""type"": ""Value"",
                    ""id"": ""27bfa70c-3b88-47aa-a92c-9bb0cec59a16"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Value"",
                    ""id"": ""889fa30d-eb57-4857-a956-de96e730ca3f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Redo"",
                    ""type"": ""Value"",
                    ""id"": ""c1156be1-7d46-4c8a-9d2e-5e910052e63e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Copy"",
                    ""type"": ""Value"",
                    ""id"": ""a7d9cd85-ea2c-45a0-9812-27af8acb48a1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cut"",
                    ""type"": ""Value"",
                    ""id"": ""67028a87-7bf3-4fad-9f23-31c19e973a4b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mirror"",
                    ""type"": ""Value"",
                    ""id"": ""a3dd6aa5-3f56-40f1-9ef1-0a2d960496e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Timing Snap"",
                    ""type"": ""Value"",
                    ""id"": ""697ed886-b7a2-4a2e-8b8d-fa629cb3c878"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Value"",
                    ""id"": ""f3ce9796-e49b-4cab-8260-359961eff90f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Toggle Grid"",
                    ""type"": ""Value"",
                    ""id"": ""72cc2d21-9209-4846-9078-3b142ca8f058"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Toggle Click To Create"",
                    ""type"": ""Value"",
                    ""id"": ""d7eeb12a-7fd6-46bb-8a67-d67d48a64f2f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Play When Holding"",
                    ""type"": ""Value"",
                    ""id"": ""906c56a2-3584-45c7-a679-d656873a9e8f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Play Or Pause"",
                    ""type"": ""Value"",
                    ""id"": ""9ec2475b-e083-4ab6-9137-f1e1c2db9746"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""319eecb4-07e2-4354-ac21-5328068fb2a1"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey(needModifier1=true)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""84338b69-3c9d-4e28-8579-8a89fc347a2f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""b84e1665-c973-4146-be51-205cc7ff479b"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""7fd164da-da3a-4bbf-80fa-206588c1799a"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""f735247b-c3ea-4272-9d4d-651f7df1aa7a"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""a85a3493-23b8-4814-9b41-c51072de6e11"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey(needModifier1=true)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""771324b2-928f-492a-afac-2ef782ac63ef"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""1aed99bf-a749-4b6b-8731-2d8e2309020e"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""4a96474e-31fe-4470-bc91-488eeee61e44"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""367112b7-6341-4826-a820-9d66d6003cc5"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""6b7b8406-1e91-4d01-8c9f-9015edac55b7"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey(needModifier1=true)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""4f8a71ec-0193-403b-a0e6-315df24c9b4f"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""0a7e327d-eb7f-42e4-b267-e875c31810dc"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""ef0c9542-2160-49d5-8d89-5191f4aecb69"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""f28c3540-8cc5-4beb-9fe6-a57a15e95f5b"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""e9670b28-b4cf-41fb-927f-b9cfe4965f57"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey(needModifier1=true)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""0abcb00d-476e-481c-8390-e175ef4820d2"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""bb454470-0fa9-4f45-a1f3-9c97f732148e"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""e6e107b9-fb6b-4816-8b34-b95f27e2f35f"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""b57463ea-68ba-4822-80cd-262dbb06c5df"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""95ef7516-08ad-4bbe-9ded-cb001b93d2c8"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey(needModifier1=true)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""a7501803-a0d7-4417-be21-aebfc5fe021c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""cf48e9e7-c448-4c55-bda7-c0ec3a816402"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""2bf19eae-8bd5-4a66-ae46-666677f135d9"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""2246909d-cb72-4520-944f-fa605391d912"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""4c3b6eec-2790-490a-8836-38575b745b41"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""8dcb385f-199c-4e57-a47b-e84f1580f94c"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""8f4b9295-9452-4708-b3c7-44379006fd5d"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""abaeb962-c302-4760-bfd7-4754150abf73"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""e3185d5e-2496-438a-b7d4-fd7256e32210"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""31f2358e-925e-4906-9205-da75aa5d7ec9"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play When Holding"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""c3af1e8b-37e8-4db1-8b2f-f31566587af2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play When Holding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""da472101-0330-4206-9d1d-6cfcb3f3c591"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play When Holding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""2897b11b-5a5a-4790-9310-116f42841a48"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play When Holding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""d8dc1cf1-5130-4e6d-ae7c-858c3c7115f2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play When Holding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""64017bfe-ef30-40c2-8872-78e40fcaae78"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Or Pause"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""6b090b2b-84b7-4990-a1d8-f9ba03a4a53c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Or Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""52828ae8-42dc-437e-a2a6-1d52e3abfabc"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Or Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""05f54591-7d44-45ff-aa48-7c37a097de9c"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Or Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""e0bbaca4-3b0f-4c79-892a-aaa836bb0003"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Or Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""4267cf68-4f96-4c30-be29-0bfd7c0b0a2b"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey(needModifier1=true)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mirror"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""48b0b425-9e74-4b68-98ea-eb6044f3d971"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mirror"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""d975a9fe-7a42-4e4f-b96e-1502289963fb"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mirror"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""37ffdad2-5f07-49b4-afb0-1eb9c4d35a01"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mirror"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""aa37989c-fb13-4d4d-acae-76924b9f9fbc"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mirror"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""604ea10d-c6e4-4a2d-ad6e-2faaa0807788"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey(needModifier1=true)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Timing Snap"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""943983ea-c143-4a6e-9a9e-744d0fe7b780"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Timing Snap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""04f52933-97d8-44ad-b823-c5d218f088b8"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Timing Snap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""3cd0bc03-efc9-43a8-8100-e98ecfb88c14"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Timing Snap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""924c9f0a-5afa-4078-9c8d-b9dadd1dab66"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Timing Snap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""0ab6a691-79c7-4c59-8f8b-b363e885b539"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Grid"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""3b9ddd2a-0085-4023-a6d6-da78fb5fcb40"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Grid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""2101e959-99fe-4ad2-8c4b-5fec01570d6f"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Grid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""f676cc43-2cc9-4905-b97d-c8646d56f8e1"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Grid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""89c677a3-a811-4e1f-b537-4a27382d99d1"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Grid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key With Modifiers"",
                    ""id"": ""599c42b2-c919-4d23-8b25-12493863cc12"",
                    ""path"": ""KeyWithModifiers"",
                    ""interactions"": ""HotKey"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Click To Create"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""key"",
                    ""id"": ""a220599d-908e-4e20-88da-a4305ef6ec00"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Click To Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""3eb42962-f353-4258-be18-4d5b6a95eff8"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Click To Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""ebb68af6-4317-4df5-925f-520afd36f3d2"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Click To Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier3"",
                    ""id"": ""4ee6bf8b-740c-4f88-bae3-f1de9a08bc95"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Click To Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Arcade Input"",
            ""id"": ""dfc1fc89-02b1-4e85-9598-9b1f3b504fb6"",
            ""actions"": [
                {
                    ""name"": ""Multiple Selection"",
                    ""type"": ""Button"",
                    ""id"": ""75a55bcc-6ccf-43d4-a9d1-b53e1e2cf773"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Range Selection"",
                    ""type"": ""Button"",
                    ""id"": ""2982c6a7-fc16-4a6a-ad91-8a0de0d23d34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2e5ec33d-b969-4ccc-a8d9-07dbb5cb2f32"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Multiple Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62702fd1-0687-431e-a718-529266c2c563"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Range Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Arcade Hotkey
            m_ArcadeHotkey = asset.FindActionMap("Arcade Hotkey", throwIfNotFound: true);
            m_ArcadeHotkey_Save = m_ArcadeHotkey.FindAction("Save", throwIfNotFound: true);
            m_ArcadeHotkey_Undo = m_ArcadeHotkey.FindAction("Undo", throwIfNotFound: true);
            m_ArcadeHotkey_Redo = m_ArcadeHotkey.FindAction("Redo", throwIfNotFound: true);
            m_ArcadeHotkey_Copy = m_ArcadeHotkey.FindAction("Copy", throwIfNotFound: true);
            m_ArcadeHotkey_Cut = m_ArcadeHotkey.FindAction("Cut", throwIfNotFound: true);
            m_ArcadeHotkey_Mirror = m_ArcadeHotkey.FindAction("Mirror", throwIfNotFound: true);
            m_ArcadeHotkey_TimingSnap = m_ArcadeHotkey.FindAction("Timing Snap", throwIfNotFound: true);
            m_ArcadeHotkey_Delete = m_ArcadeHotkey.FindAction("Delete", throwIfNotFound: true);
            m_ArcadeHotkey_ToggleGrid = m_ArcadeHotkey.FindAction("Toggle Grid", throwIfNotFound: true);
            m_ArcadeHotkey_ToggleClickToCreate = m_ArcadeHotkey.FindAction("Toggle Click To Create", throwIfNotFound: true);
            m_ArcadeHotkey_PlayWhenHolding = m_ArcadeHotkey.FindAction("Play When Holding", throwIfNotFound: true);
            m_ArcadeHotkey_PlayOrPause = m_ArcadeHotkey.FindAction("Play Or Pause", throwIfNotFound: true);
            // Arcade Input
            m_ArcadeInput = asset.FindActionMap("Arcade Input", throwIfNotFound: true);
            m_ArcadeInput_MultipleSelection = m_ArcadeInput.FindAction("Multiple Selection", throwIfNotFound: true);
            m_ArcadeInput_RangeSelection = m_ArcadeInput.FindAction("Range Selection", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Arcade Hotkey
        private readonly InputActionMap m_ArcadeHotkey;
        private IArcadeHotkeyActions m_ArcadeHotkeyActionsCallbackInterface;
        private readonly InputAction m_ArcadeHotkey_Save;
        private readonly InputAction m_ArcadeHotkey_Undo;
        private readonly InputAction m_ArcadeHotkey_Redo;
        private readonly InputAction m_ArcadeHotkey_Copy;
        private readonly InputAction m_ArcadeHotkey_Cut;
        private readonly InputAction m_ArcadeHotkey_Mirror;
        private readonly InputAction m_ArcadeHotkey_TimingSnap;
        private readonly InputAction m_ArcadeHotkey_Delete;
        private readonly InputAction m_ArcadeHotkey_ToggleGrid;
        private readonly InputAction m_ArcadeHotkey_ToggleClickToCreate;
        private readonly InputAction m_ArcadeHotkey_PlayWhenHolding;
        private readonly InputAction m_ArcadeHotkey_PlayOrPause;
        public struct ArcadeHotkeyActions
        {
            private @AdeInputControl m_Wrapper;
            public ArcadeHotkeyActions(@AdeInputControl wrapper) { m_Wrapper = wrapper; }
            public InputAction @Save => m_Wrapper.m_ArcadeHotkey_Save;
            public InputAction @Undo => m_Wrapper.m_ArcadeHotkey_Undo;
            public InputAction @Redo => m_Wrapper.m_ArcadeHotkey_Redo;
            public InputAction @Copy => m_Wrapper.m_ArcadeHotkey_Copy;
            public InputAction @Cut => m_Wrapper.m_ArcadeHotkey_Cut;
            public InputAction @Mirror => m_Wrapper.m_ArcadeHotkey_Mirror;
            public InputAction @TimingSnap => m_Wrapper.m_ArcadeHotkey_TimingSnap;
            public InputAction @Delete => m_Wrapper.m_ArcadeHotkey_Delete;
            public InputAction @ToggleGrid => m_Wrapper.m_ArcadeHotkey_ToggleGrid;
            public InputAction @ToggleClickToCreate => m_Wrapper.m_ArcadeHotkey_ToggleClickToCreate;
            public InputAction @PlayWhenHolding => m_Wrapper.m_ArcadeHotkey_PlayWhenHolding;
            public InputAction @PlayOrPause => m_Wrapper.m_ArcadeHotkey_PlayOrPause;
            public InputActionMap Get() { return m_Wrapper.m_ArcadeHotkey; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ArcadeHotkeyActions set) { return set.Get(); }
            public void SetCallbacks(IArcadeHotkeyActions instance)
            {
                if (m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface != null)
                {
                    @Save.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnSave;
                    @Save.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnSave;
                    @Save.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnSave;
                    @Undo.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnUndo;
                    @Undo.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnUndo;
                    @Undo.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnUndo;
                    @Redo.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnRedo;
                    @Redo.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnRedo;
                    @Redo.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnRedo;
                    @Copy.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnCopy;
                    @Copy.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnCopy;
                    @Copy.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnCopy;
                    @Cut.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnCut;
                    @Cut.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnCut;
                    @Cut.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnCut;
                    @Mirror.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnMirror;
                    @Mirror.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnMirror;
                    @Mirror.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnMirror;
                    @TimingSnap.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnTimingSnap;
                    @TimingSnap.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnTimingSnap;
                    @TimingSnap.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnTimingSnap;
                    @Delete.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnDelete;
                    @Delete.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnDelete;
                    @Delete.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnDelete;
                    @ToggleGrid.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnToggleGrid;
                    @ToggleGrid.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnToggleGrid;
                    @ToggleGrid.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnToggleGrid;
                    @ToggleClickToCreate.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnToggleClickToCreate;
                    @ToggleClickToCreate.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnToggleClickToCreate;
                    @ToggleClickToCreate.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnToggleClickToCreate;
                    @PlayWhenHolding.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnPlayWhenHolding;
                    @PlayWhenHolding.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnPlayWhenHolding;
                    @PlayWhenHolding.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnPlayWhenHolding;
                    @PlayOrPause.started -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnPlayOrPause;
                    @PlayOrPause.performed -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnPlayOrPause;
                    @PlayOrPause.canceled -= m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface.OnPlayOrPause;
                }
                m_Wrapper.m_ArcadeHotkeyActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Save.started += instance.OnSave;
                    @Save.performed += instance.OnSave;
                    @Save.canceled += instance.OnSave;
                    @Undo.started += instance.OnUndo;
                    @Undo.performed += instance.OnUndo;
                    @Undo.canceled += instance.OnUndo;
                    @Redo.started += instance.OnRedo;
                    @Redo.performed += instance.OnRedo;
                    @Redo.canceled += instance.OnRedo;
                    @Copy.started += instance.OnCopy;
                    @Copy.performed += instance.OnCopy;
                    @Copy.canceled += instance.OnCopy;
                    @Cut.started += instance.OnCut;
                    @Cut.performed += instance.OnCut;
                    @Cut.canceled += instance.OnCut;
                    @Mirror.started += instance.OnMirror;
                    @Mirror.performed += instance.OnMirror;
                    @Mirror.canceled += instance.OnMirror;
                    @TimingSnap.started += instance.OnTimingSnap;
                    @TimingSnap.performed += instance.OnTimingSnap;
                    @TimingSnap.canceled += instance.OnTimingSnap;
                    @Delete.started += instance.OnDelete;
                    @Delete.performed += instance.OnDelete;
                    @Delete.canceled += instance.OnDelete;
                    @ToggleGrid.started += instance.OnToggleGrid;
                    @ToggleGrid.performed += instance.OnToggleGrid;
                    @ToggleGrid.canceled += instance.OnToggleGrid;
                    @ToggleClickToCreate.started += instance.OnToggleClickToCreate;
                    @ToggleClickToCreate.performed += instance.OnToggleClickToCreate;
                    @ToggleClickToCreate.canceled += instance.OnToggleClickToCreate;
                    @PlayWhenHolding.started += instance.OnPlayWhenHolding;
                    @PlayWhenHolding.performed += instance.OnPlayWhenHolding;
                    @PlayWhenHolding.canceled += instance.OnPlayWhenHolding;
                    @PlayOrPause.started += instance.OnPlayOrPause;
                    @PlayOrPause.performed += instance.OnPlayOrPause;
                    @PlayOrPause.canceled += instance.OnPlayOrPause;
                }
            }
        }
        public ArcadeHotkeyActions @ArcadeHotkey => new ArcadeHotkeyActions(this);

        // Arcade Input
        private readonly InputActionMap m_ArcadeInput;
        private IArcadeInputActions m_ArcadeInputActionsCallbackInterface;
        private readonly InputAction m_ArcadeInput_MultipleSelection;
        private readonly InputAction m_ArcadeInput_RangeSelection;
        public struct ArcadeInputActions
        {
            private @AdeInputControl m_Wrapper;
            public ArcadeInputActions(@AdeInputControl wrapper) { m_Wrapper = wrapper; }
            public InputAction @MultipleSelection => m_Wrapper.m_ArcadeInput_MultipleSelection;
            public InputAction @RangeSelection => m_Wrapper.m_ArcadeInput_RangeSelection;
            public InputActionMap Get() { return m_Wrapper.m_ArcadeInput; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ArcadeInputActions set) { return set.Get(); }
            public void SetCallbacks(IArcadeInputActions instance)
            {
                if (m_Wrapper.m_ArcadeInputActionsCallbackInterface != null)
                {
                    @MultipleSelection.started -= m_Wrapper.m_ArcadeInputActionsCallbackInterface.OnMultipleSelection;
                    @MultipleSelection.performed -= m_Wrapper.m_ArcadeInputActionsCallbackInterface.OnMultipleSelection;
                    @MultipleSelection.canceled -= m_Wrapper.m_ArcadeInputActionsCallbackInterface.OnMultipleSelection;
                    @RangeSelection.started -= m_Wrapper.m_ArcadeInputActionsCallbackInterface.OnRangeSelection;
                    @RangeSelection.performed -= m_Wrapper.m_ArcadeInputActionsCallbackInterface.OnRangeSelection;
                    @RangeSelection.canceled -= m_Wrapper.m_ArcadeInputActionsCallbackInterface.OnRangeSelection;
                }
                m_Wrapper.m_ArcadeInputActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @MultipleSelection.started += instance.OnMultipleSelection;
                    @MultipleSelection.performed += instance.OnMultipleSelection;
                    @MultipleSelection.canceled += instance.OnMultipleSelection;
                    @RangeSelection.started += instance.OnRangeSelection;
                    @RangeSelection.performed += instance.OnRangeSelection;
                    @RangeSelection.canceled += instance.OnRangeSelection;
                }
            }
        }
        public ArcadeInputActions @ArcadeInput => new ArcadeInputActions(this);
        public interface IArcadeHotkeyActions
        {
            void OnSave(InputAction.CallbackContext context);
            void OnUndo(InputAction.CallbackContext context);
            void OnRedo(InputAction.CallbackContext context);
            void OnCopy(InputAction.CallbackContext context);
            void OnCut(InputAction.CallbackContext context);
            void OnMirror(InputAction.CallbackContext context);
            void OnTimingSnap(InputAction.CallbackContext context);
            void OnDelete(InputAction.CallbackContext context);
            void OnToggleGrid(InputAction.CallbackContext context);
            void OnToggleClickToCreate(InputAction.CallbackContext context);
            void OnPlayWhenHolding(InputAction.CallbackContext context);
            void OnPlayOrPause(InputAction.CallbackContext context);
        }
        public interface IArcadeInputActions
        {
            void OnMultipleSelection(InputAction.CallbackContext context);
            void OnRangeSelection(InputAction.CallbackContext context);
        }
    }
}
